### ISSUE TITLE
Error compiling `File storage/database.rs does not exist.`

### ISSUE THREAD

**Issue by igorgue** [edfloreshz/done#12]
**Describe the bug**
When I try to run: `meson . _build --prefix=/usr` I get the following error:

```src/meson.build:11:0: ERROR: File storage/database.rs does not exist.```

It also happens when I click *build* on **Gnome Builder**

I'm on `main` git hash: `a521f76f729b6428cd6096165be6add9fd05d8b1`

**Comment by igorgue** [comment]
To compile I have to remove these lines:
```
diff --git a/src/meson.build b/src/meson.build
index c6f716e..75688ca 100644
--- a/src/meson.build
+++ b/src/meson.build
@@ -22,15 +22,15 @@ rust_sources = files(
   'models/list.rs',
   'models/task.rs',
   'models/mod.rs',
-  'storage/database.rs',
+  #'storage/database.rs',
   'storage/mod.rs',
   'widgets/app.rs',
-  'widgets/task_container.rs',
-  'widgets/details.rs',
-  'widgets/list.rs',
+  #'widgets/task_container.rs',
+  #'widgets/details.rs',
+  #'widgets/list.rs',
   'widgets/mod.rs',
-  'widgets/sidebar.rs',
-  'widgets/task_list.rs',
+  #'widgets/sidebar.rs',
+  #'widgets/task_list.rs',
 )
 
 sources = [cargo_sources, rust_sources]
```
How are you compiling the project right now?

**Comment by edfloreshz** [comment]
Hello, thank you for reporting this, I'm aware of this issue and will fix it as soon as I'm back from vacation.

You're welcome to submit a PR and I'll happily merge it.

You can remove the full array and it will still compile, it's supposed to have every file in the project but I didn't update it after making some changes.

You can still compile it with `cargo`.
