### ISSUE TITLE
Option to delete created lists

### ISSUE THREAD

**Issue by IngrownMink4** [edfloreshz/done#19]
**Describe the bug**
You can't delete a list

**To Reproduce**

1. Right Click on the list that you want to delete
2. Nothing happens

**Expected behavior**
Should display a small menu that gives the option to delete and rewrite a list created by the user.

**Desktop (please complete the following information):**
 - OS: Manjaro GNOME

**Comment by edfloreshz** [comment]
Thank you for adding this, I'm working to implement this for the next release.
