### ISSUE TITLE
Tasks do not actually delete

### ISSUE THREAD

**Issue by adamijak** [edfloreshz/done#9]
Steps to reproduce
1. Create few tasks
2. Click delete on these tasks, they will disapear
3. Change view to some other list
4. Change view back to previous and tasks are still present

**Comment by edfloreshz** [comment]
As a workaround for now, you can switch to another list and then come back and delete will work.

This issue has been fixed in the [relm/0.5.0](https://github.com/edfloreshz/done/tree/relm/0.5.0) branch.

**Comment by edfloreshz** [comment]
Fixed in #15
